// live_latest.js — GET /api/latest: near-real-time market snapshot.
//
// The static Pages payload (data/latest.json) is regenerated by the Pi pipeline
// every 30 min during market hours (and daily at 07:19). This route re-serves
// that snapshot but overlays fresh quotes for the index strip — plus VIX, 10Y
// yield and USD/CAD — fetched from Yahoo's public chart API on demand, cached
// in-isolate for 30s so the frontend's 5-second poll never hammers Yahoo.
//
// Fail-open contract: any upstream failure degrades to the static snapshot
// rather than an error; only if the static snapshot itself is unreachable does
// the route return 502 (the frontend then falls back to /data/latest.json).
// The response shape is identical to the static file plus an optional
// `live_refreshed_at` ISO timestamp, so existing zod schemas keep working.

const YAHOO_UA = { 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36' };

// (symbol, display ticker, market_summary field). `field` mirrors where the
// pipeline stashes dedicated values: vix, ten_year_yield, fx. The index strip
// entry (with change_pct) is always produced for symbols 1-7.
const LIVE_SYMBOLS = [
  { symbol: '^GSPC',    ticker: 'S&P 500',     field: null },
  { symbol: '^DJI',     ticker: 'Dow Jones',   field: null },
  { symbol: '^IXIC',    ticker: 'NASDAQ',      field: null },
  { symbol: '^RUT',     ticker: 'Russell 2000', field: null },
  { symbol: '^GSPTSE',  ticker: 'TSX',         field: null },
  { symbol: '^VIX',     ticker: 'VIX',         field: 'vix' },
  { symbol: '^TNX',     ticker: '10Y Yield',   field: 'ten_year_yield' },
  { symbol: 'USDCAD=X', ticker: 'USD/CAD',     field: 'fx' },
];

const STATIC_LATEST_URL = 'https://maplegamma.com/data/latest.json';
const CACHE_TTL_MS = 30_000;

// Per-isolate TTL cache. Isolates are short-lived under load, so this bounds
// Yahoo traffic without needing KV or Cache API bookkeeping.
const cache = { at: 0, payload: null };

/** Test-only: drop the TTL cache so a fresh request re-fetches upstreams. */
export function resetLiveCacheForTests() {
  cache.at = 0;
  cache.payload = null;
}

/** Parse a Yahoo v8 chart payload into { price, change_pct } (2dp, like the pipeline). */
export function parseYahooChart(payload) {
  const r = payload?.chart?.result?.[0];
  if (!r) return null;
  const closes = (r?.indicators?.quote?.[0]?.close || []).filter((v) => v != null);
  if (closes.length < 2) return null;
  const price = closes[closes.length - 1];
  const prev = closes[closes.length - 2];
  if (!prev) return null;
  return {
    price: Math.round(price * 100) / 100,
    change_pct: Math.round(((price - prev) / prev) * 10000) / 100,
  };
}

async function fetchLiveQuote(symbol) {
  const url = `https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=5d&interval=1d`;
  const res = await fetch(url, { headers: YAHOO_UA });
  if (!res.ok) throw new Error(`yahoo ${symbol}: HTTP ${res.status}`);
  return parseYahooChart(await res.json());
}

/** Overlay live quotes onto the static snapshot in place; returns the merged object. */
export function mergeLive(staticData, liveBySymbol) {
  const ms = staticData.market_summary || (staticData.market_summary = {});
  const byTicker = new Map((ms.indices || []).map((i) => [i.ticker, i]));
  for (const { symbol, ticker, field } of LIVE_SYMBOLS) {
    const q = liveBySymbol.get(symbol);
    if (!q) continue; // keep the static entry for this symbol
    byTicker.set(ticker, { ticker, price: q.price, change_pct: q.change_pct });
    if (field === 'vix') ms.vix = q.price;
    if (field === 'ten_year_yield') ms.ten_year_yield = Math.round(q.price * 1000) / 1000;
    if (field === 'fx') ms.fx_rates = [{ pair: 'USD/CAD', price: q.price }];
  }
  ms.indices = [...byTicker.values()];
  return staticData;
}

export function mountLiveLatest(app) {
  app.get('/api/latest', async (c) => {
    if (cache.payload && Date.now() - cache.at < CACHE_TTL_MS) {
      return c.json(cache.payload, 200, { 'Cache-Control': 'public, max-age=30' });
    }

    const staticRes = await fetch(STATIC_LATEST_URL, { headers: YAHOO_UA }).catch(() => null);
    if (!staticRes || !staticRes.ok) {
      return c.json({ error: 'upstream snapshot unavailable' }, 502, { 'Cache-Control': 'no-store' });
    }
    const staticData = await staticRes.json();

    const liveBySymbol = new Map();
    await Promise.all(
      LIVE_SYMBOLS.map(async ({ symbol }) => {
        try {
          const q = await fetchLiveQuote(symbol);
          if (q) liveBySymbol.set(symbol, q);
        } catch {
          // best-effort: keep the static value for this symbol
        }
      }),
    );

    if (liveBySymbol.size) {
      mergeLive(staticData, liveBySymbol);
      staticData.live_refreshed_at = new Date().toISOString();
    }
    // Cache both the overlaid and the static-only path: on a full Yahoo
    // failure the 5s frontend poll must not hammer a throttled upstream.
    cache.at = Date.now();
    cache.payload = staticData;
    return c.json(staticData, 200, { 'Cache-Control': 'public, max-age=30' });
  });
}
